# Generated by Django 5.1.7 on 2025-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LITReview', '0002_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=2048),
        ),
    ]
