# Generated by Django 5.1.7 on 2025-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LITReview', '0003_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=8192),
        ),
    ]
